/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(imageToPdf)'}/scan-file` | `/scan-file`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/invoice-editor` | `/invoice-editor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/scan-invoice` | `/scan-invoice`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(imageToPdf)'}/scan-file` | `/scan-file`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/invoice-editor` | `/invoice-editor`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/scan-invoice` | `/scan-invoice`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(imageToPdf)'}/scan-file${`?${string}` | `#${string}` | ''}` | `/scan-file${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/invoice-editor${`?${string}` | `#${string}` | ''}` | `/invoice-editor${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/scan-invoice${`?${string}` | `#${string}` | ''}` | `/scan-invoice${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(imageToPdf)'}/scan-file` | `/scan-file`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/invoice-editor` | `/invoice-editor`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(InvoiceGeneratorScreens)'}/scan-invoice` | `/scan-invoice`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
